Repository IF-115-Ruby/OSBB, pull requests merged in 2020-11, with the labels that each got.

#72 Styling mailer
  .env.template
  Gemfile
  Gemfile.lock
  app/assets/images/if-mailer.png
  app/mailers/user_mailer.rb
  app/views/admin_mailer/admin_notification.html.slim
  app/views/devise/mailer/reset_password_instructions.html.slim
  app/views/layouts/mailer.html.slim
  app/views/user_mailer/send_welcome_email.html.slim
  config/application.rb
  config/locales/en.yml
  config/locales/ua.yml
  vendor/assets/stylesheets/mailer.scss
Labels: need review

#81 strong_migration gem was added
  Gemfile
  Gemfile.lock
  config/database.yml
  config/initializers/strong_migrations.rb
Labels: need merge, need review

#67 Export pdf
  Gemfile
  Gemfile.lock
  app/assets/stylesheets/receipt.scss
  app/controllers/account/payments_controller.rb
  app/javascript/stylesheets/_colors.scss
  app/views/account/payments/index.html.slim
  app/views/account/payments/receipt_pdf.html.slim
  app/views/account/payments/show.html.slim
  app/views/layouts/receipt_pdf.html.slim
  config/initializers/assets.rb
  config/initializers/mime_types.rb
  config/initializers/wicked_pdf.rb
  config/locales/en.yml
  config/locales/ua.yml
  config/routes.rb
  spec/controllers/account/payments_controller_spec.rb
  spec/rails_helper.rb
Labels: need review

#76 Add .csv .xlsx and .xlsx import for companies
  Gemfile
  Gemfile.lock
  app/controllers/account/admin/companies_controller.rb
  app/importers/applications_import.rb
  app/importers/companies_import.rb
  app/javascript/stylesheets/admin_form.scss
  app/views/account/admin/companies/index.html.slim
  app/views/account/admin/companies/new_import.html.slim
  app/views/account/admin/companies/new_import.xlsx.axlsx
  config/initializers/pluralization.rb
  config/locales/en.yml
  config/locales/plurals.rb
  config/locales/ua.yml
  config/routes.rb
  spec/controllers/account/admin/companies_controller_spec.rb
  spec/fixtures/files/companies-incorrect.csv
  spec/fixtures/files/companies-incorrect.xls
  spec/fixtures/files/companies-incorrect.xlsx
  spec/fixtures/files/companies.csv
  spec/fixtures/files/companies.xls
  spec/fixtures/files/companies.xlsx
  spec/fixtures/files/not-csv
  spec/importers/companies_import_spec.rb
Labels: need review

#73 Import xls for billing contracts
  .rubocop.yml
  .travis.yml
  Gemfile
  Gemfile.lock
  app/controllers/account/admin/billing_contracts_controller.rb
  app/importers/billing_contracts_import.rb
  app/javascript/stylesheets/account/style.scss
  app/javascript/stylesheets/admin_all_component.scss
  app/models/billing_contract.rb
  app/views/account/admin/billing_contracts/_form-import.html.slim
  app/views/account/admin/billing_contracts/_form.html.slim
  app/views/account/admin/billing_contracts/index.html.slim
  app/views/account/admin/billing_contracts/index.xlsx.axlsx
  app/views/account/admin/billing_contracts/new_import.html.slim
  app/views/account/admin/billing_contracts/new_import.xlsx.axlsx
  app/views/devise/sessions/new.html.slim
  config/application.rb
  config/locales/en.yml
  config/locales/ua.yml
  config/routes.rb
  spec/controllers/account/admin/billing_contracts_controller_spec.rb
  spec/controllers/account/admin/osbbs_controller_spec.rb
  spec/fixtures/files/b-contracts/billing-contracts-untrue.xlsx
  spec/fixtures/files/b-contracts/billing-contracts.xlsx
  spec/fixtures/files/b-contracts/billing_contracts-untrue.csv
  spec/fixtures/files/b-contracts/billing_contracts.csv
  spec/fixtures/files/empty.txt
  spec/importers/billing_contracts_import_spec.rb
  spec/spec_helper.rb
Labels: need review

#83 Done payments import per company from xls, xlsx and csv
  Gemfile.lock
  app/controllers/account/admin/payments_controller.rb
  app/importers/applications_import.rb
  app/importers/billing_contracts_import.rb
  app/importers/payments_import.rb
  app/views/account/admin/companies/index.html.slim
  app/views/account/admin/payments/new_import.html.slim
  app/views/account/admin/payments/new_import.xlsx.axlsx
  config/locales/en.yml
  config/locales/ua.yml
  config/routes.rb
  spec/controllers/account/admin/payments_controller_spec.rb
  spec/fixtures/files/not_csv_file
  spec/fixtures/files/payments_csv.csv
  spec/fixtures/files/payments_incorrect_csv.csv
  spec/fixtures/files/payments_xls.xls
  spec/fixtures/files/payments_xlsx.xlsx
  spec/importers/payments_import_spec.rb
Labels: !ready for review!, need review

#74 xls import for bills per company
  app/controllers/account/admin/bills_controller.rb
  app/importers/bills_import.rb
  app/importers/concerns/company_data_loader.rb
  app/importers/payments_import.rb
  app/views/account/admin/bills/new_import.html.slim
  app/views/account/admin/bills/new_import.xlsx.axlsx
  app/views/account/admin/companies/index.html.slim
  config/locales/en.yml
  config/locales/ua.yml
  config/routes.rb
  spec/controllers/account/admin/bills_controller_spec.rb
  spec/fixtures/files/bills-incorrect.csv
  spec/fixtures/files/bills.csv
  spec/fixtures/files/bills.xls
  spec/fixtures/files/bills.xlsx
  spec/importers/bills_import_spec.rb
Labels: !ready for review!, need review

#85 Adding pretender gem
  Gemfile
  Gemfile.lock
  app/controllers/account/admin/admin_controller.rb
  app/controllers/application_controller.rb
  app/javascript/stylesheets/account/style.scss
  app/models/user.rb
  app/views/account/admin/users/_user.html.slim
  app/views/shared/account/_header.html.slim
  config/locales/en.yml
  config/locales/ua.yml
  config/routes.rb
  public/User_Account.png
  public/file-20200618-41213-iu7wbs.jpg
  public/user_index_User_Account.png
  public/user_index_file-20200618-41213-iu7wbs.jpg
  public/user_show_User_Account.png
  public/user_show_file-20200618-41213-iu7wbs.jpg
  spec/features/user_impersonate_spec.rb
  spec/rails_helper.rb
Labels: !ready for review!, need review

#89 Implement breadcrumbs with personal view helper
  app/helpers/application_helper.rb
  app/javascript/stylesheets/application.scss
  app/javascript/stylesheets/breadcrumb.scss
  app/views/account/admin/billing_contracts/edit.html.slim
  app/views/account/admin/billing_contracts/index.html.slim
  app/views/account/admin/billing_contracts/new.html.slim
  app/views/account/admin/billing_contracts/new_import.html.slim
  app/views/account/admin/billing_contracts/show.html.slim
  app/views/account/admin/bills/new_import.html.slim
  app/views/account/admin/companies/edit.html.slim
  app/views/account/admin/companies/index.html.slim
  app/views/account/admin/companies/new.html.slim
  app/views/account/admin/companies/new_import.html.slim
  app/views/account/admin/companies/show.html.slim
  app/views/account/admin/osbbs/edit.html.slim
  app/views/account/admin/osbbs/index.html.slim
  app/views/account/admin/osbbs/new.html.slim
  app/views/account/admin/osbbs/show.html.slim
  app/views/account/admin/payments/new_import.html.slim
  app/views/account/admin/users/index.html.slim
  app/views/account/shared/_breadcrumbs.html.slim
  app/views/account/users/edit.html.slim
  app/views/account/users/show.html.slim
  app/views/account/utility_providers/_search_form.html.slim
  app/views/account/utility_providers/index.html.slim
  app/views/account/utility_providers/new.html.slim
  app/views/account/utility_providers/show.html.slim
  app/views/devise/registrations/edit.html.slim
  app/views/layouts/account.html.slim
Labels: need review

#88 user edit move to profile
  Gemfile
  Gemfile.lock
  app/controllers/account/users_controller.rb
  app/models/user.rb
  app/views/account/users/_address_fields.html.slim
  app/views/account/users/_form.html.slim
  app/views/account/users/edit.html.slim
  app/views/account/users/show.html.slim
  config/locales/en.yml
  config/locales/ua.yml
  config/routes.rb
  spec/controllers/account/users_controller_spec.rb
  spec/models/user_spec.rb
  spec/rails_helper.rb
Labels: need review

#79 utility providers page and user payment
  .rubocop.yml
  Gemfile.lock
  app/controllers/account/utility_providers_controller.rb
  app/helpers/account/utility_providers_helper.rb
  app/javascript/stylesheets/application.scss
  app/javascript/stylesheets/basic.scss
  app/javascript/stylesheets/osbbs.scss
  app/javascript/stylesheets/users.scss
  app/javascript/stylesheets/utility_providers.scss
  app/models/bill.rb
  app/models/billing_contract.rb
  app/models/payment.rb
  app/models/user.rb
  app/views/account/admin/users/_user.html.slim
  app/views/account/utility_providers/_utility_provider.html.slim
  app/views/account/utility_providers/index.html.slim
  app/views/account/utility_providers/show.html.slim
  config/locales/en.yml
  config/locales/ua.yml
  db/seeds.rb
  spec/factories/bills.rb
  spec/factories/payments.rb
  spec/helpers/account/users_helper_spec.rb
  spec/helpers/account/utility_providers_helper_spec.rb
  spec/helpers/billing_contracts_helper_spec.rb
  spec/helpers/controller_helper_spec.rb
  spec/models/bill_spec.rb
  spec/models/billing_contract_spec.rb
  spec/models/payment_spec.rb
  spec/models/user_spec.rb
Labels: !ready for review!, need review

#90 finish task calculate jobs
  .rubocop.yml
  Gemfile
  Gemfile.lock
  app/controllers/account/admin/companies_controller.rb
  app/importers/companies_import.rb
  app/models/bill.rb
  app/models/company.rb
  app/models/meter_reading.rb
  app/models/payment.rb
  app/views/account/admin/companies/_form.html.slim
  app/views/account/admin/companies/new_import.xlsx.axlsx
  app/views/account/admin/companies/show.html.slim
  app/workers/calculate_bill_worker.rb
  config/initializers/sidekiq.rb
  config/locales/en.yml
  config/locales/ua.yml
  config/schedule.yml
  db/migrate/20201110095904_add_coefficient_to_companies.rb
  db/migrate/20201110143645_add_meter_reading_to_bills.rb
  db/schema.rb
  db/seeds.rb
  spec/factories/bills.rb
  spec/factories/company.rb
  spec/factories/payments.rb
  spec/fixtures/files/companies.csv
  spec/fixtures/files/companies.xls
  spec/fixtures/files/companies.xlsx
  spec/models/bill_spec.rb
  spec/models/company_spec.rb
  spec/workers/calculate_bill_worker_spec.rb
Labels: need merge, need review

#92 Payments show page and link to generated pdf
  Gemfile.lock
  app/controllers/account/meter_readings_controller.rb
  app/controllers/account/payments_controller.rb
  app/controllers/account/utility_providers_controller.rb
  app/helpers/ransack_helper.rb
  app/views/account/admin/payments/new_import.html.slim
  app/views/account/payments/_payments.html.slim
  app/views/account/payments/index.html.slim
  app/views/account/payments/receipt_pdf.html.slim
  app/views/account/payments/show.html.slim
  app/views/account/utility_providers/show.html.slim
  app/views/layouts/receipt_pdf.html.slim
  config/routes.rb
  spec/controllers/account/payments_controller_spec.rb
  spec/controllers/account/utility_providers_controller_spec.rb
  spec/factories/payments.rb
Labels: !ready for review!, need review

#71 Osbb news
  Gemfile
  Gemfile.lock
  app/assets/javascripts/ckeditor/config.js
  app/controllers/account/news_controller.rb
  app/javascript/stylesheets/_colors.scss
  app/javascript/stylesheets/application.scss
  app/javascript/stylesheets/news.scss
  app/models/ckeditor/asset.rb
  app/models/ckeditor/attachment_file.rb
  app/models/ckeditor/picture.rb
  app/models/news.rb
  app/models/osbb.rb
  app/models/user.rb
  app/policies/base_policy.rb
  app/policies/news_policy.rb
  app/uploaders/ckeditor_attachment_file_uploader.rb
  app/uploaders/ckeditor_picture_uploader.rb
  app/uploaders/image_uploader.rb
  app/views/account/admin/osbbs/edit.html.slim
  app/views/account/admin/osbbs/index.html.slim
  app/views/account/admin/osbbs/new.html.slim
  app/views/account/admin/osbbs/show.html.slim
  app/views/account/news/_form.html.slim
  app/views/account/news/_news.html.slim
  app/views/account/news/edit.html.slim
  app/views/account/news/index.html.slim
  app/views/account/news/new.html.slim
  app/views/account/news/show.html.slim
  app/views/shared/account/_user_cabinet.html.slim
  config/application.rb
  config/initializers/assets.rb
  config/initializers/ckeditor.rb
  config/locales/en.yml
  config/locales/ua.yml
  config/routes.rb
  db/migrate/20201103134924_create_news.rb
  db/migrate/20201103135032_add_images_to_news.rb
  db/migrate/20201103180127_create_ckeditor_assets.rb
  db/schema.rb
  spec/controllers/account/news_controller_spec.rb
  spec/factories/news.rb
  spec/models/news_spec.rb
  spec/models/osbb_spec.rb
  spec/models/user_spec.rb
  spec/policies/news_policy_spec.rb
  spec/rails_helper.rb
Labels: !ready for review!, need review

#99 fix clean up uploaded files for tests
  app/uploaders/avatar_uploader.rb
  db/seeds.rb
  spec/factories/news.rb
  spec/factories/users.rb
  spec/rails_helper.rb
Labels: !ready for review!

#103 FE React for Rails
  Gemfile
  Gemfile.lock
  app/javascript/components/.keep
  app/javascript/packs/application.js
  app/javascript/packs/reactrailsujs.js
  app/javascript/packs/server_rendering.js
  babel.config.js
  config/application.rb
  config/webpacker.yml
  package.json
  yarn.lock
Labels: need review

#93 user_creates/associates_with_osbb
  .rubocop.yml
  .travis.yml
  Gemfile
  Gemfile.lock
  app/controllers/account/admin/billing_contracts_controller.rb
  app/controllers/account/admin/osbbs_controller.rb
  app/controllers/account/osbbs_controller.rb
  app/controllers/account/users_controller.rb
  app/javascript/packs/application.js
  app/javascript/packs/osbbs.js
  app/javascript/packs/personal_info_edit.js
  app/javascript/stylesheets/application.scss
  app/javascript/stylesheets/breadcrumb.scss
  app/javascript/stylesheets/osbbs.scss
  app/javascript/stylesheets/users.scss
  app/mailers/user_mailer.rb
  app/models/concerns/searchable.rb
  app/models/osbb.rb
  app/models/user.rb
  app/policies/admin_policy.rb
  app/policies/bill_policy.rb
  app/policies/billing_contract_policy.rb
  app/policies/company_policy.rb
  app/policies/osbb_policy.rb
  app/policies/payment_policy.rb
  app/policies/user_policy.rb
  app/views/account/admin/osbbs/_form.html.slim
  app/views/account/admin/osbbs/new.html.slim
  app/views/account/admin/osbbs/show.html.slim
  app/views/account/osbbs/search.json.jbuilder
  app/views/account/users/_assign_form.html.slim
  app/views/account/users/new_assign_osbb.html.slim
  app/views/shared/account/_user_cabinet.html.slim
  app/views/user_mailer/send_assign_notification.slim
  app/workers/new_member_worker.rb
  config/initializers/elasticsearch.rb
  config/initializers/sidekiq.rb
  config/locales/en.yml
  config/routes.rb
  db/seeds.rb
  package.json
  spec/controllers/account/admin/osbbs_controller_spec.rb
  spec/controllers/account/osbbs_controller_spec.rb
  spec/controllers/account/users_controller_spec.rb
  spec/features/osbbs_crud_spec.rb
  spec/features/user_assign_osbb_spec.rb
  spec/features/user_impersonate_spec.rb
  spec/mailers/previews/user_mailer_preview.rb
  spec/mailers/user_mailer_spec.rb
  spec/models/billing_contract_spec.rb
  spec/policies/osbb_policy_spec.rb
  spec/policies/user_policy_spec.rb
  spec/workers/new_member_worker_spec.rb
  yarn.lock
Labels: need review

#108 User show page on React
  app/assets/images/svg_icon_delete.svg
  app/assets/images/svg_icon_return.svg
  app/controllers/account/admin/users_controller.rb
  app/controllers/account/users_controller.rb
  app/controllers/api/v1/users_controller.rb
  app/controllers/user/registrations_controller.rb
  app/javascript/components/users/show/Control.jsx
  app/javascript/components/users/show/ShowUser.jsx
  app/javascript/components/users/show/_InfoHelper.jsx
  app/javascript/stylesheets/_colors.scss
  app/javascript/stylesheets/_fadeIn.scss
  app/javascript/stylesheets/admin_form.scss
  app/javascript/stylesheets/application.scss
  app/javascript/stylesheets/basic.scss
  app/javascript/stylesheets/users.scss
  app/models/osbb.rb
  app/models/user.rb
  app/policies/admin_policy.rb
  app/policies/news_policy.rb
  app/policies/user_policy.rb
  app/uploaders/avatar_uploader.rb
  app/views/account/users/show.html.slim
  app/views/api/v1/users/_user.json.jbuilder
  app/views/api/v1/users/show.json.jbuilder
  config/routes.rb
  config/webpacker.yml
  db/seeds.rb
  package-lock.json
  package.json
  spec/controllers/account/admin/users_controller_spec.rb
  spec/controllers/api/v1/users_controller_spec.rb
  spec/controllers/registrations_controller_spec.rb
  spec/features/user_impersonate_spec.rb
  spec/mailers/user_mailer_spec.rb
  spec/models/user_spec.rb
  spec/policies/news_policy_spec.rb
  spec/workers/new_member_worker_spec.rb
  yarn.lock
Labels: need merge

#116 Show page for news on react
  app/controllers/api/api_controller.rb
  app/controllers/api/v1/news_controller.rb
  app/javascript/components/my_osbb/News/ShowNews.jsx
  app/javascript/components/my_osbb/News/ShowNews.module.scss
  app/uploaders/image_uploader.rb
  app/views/account/news/show.html.slim
  app/views/api/v1/news/index.json.jbuilder
  app/views/api/v1/news/show.json.jbuilder
  bin/webpack
  bin/webpack-dev-server
  config/routes.rb
  package.json
  public/No-image.jpg
  public/no-image.png
  spec/controllers/api/v1/news_controller_spec.rb
  spec/factories/news.rb
  yarn.lock
Labels: need review

#115 Add auth Facebook
  Gemfile
  Gemfile.lock
  app/controllers/user/omniauth_callbacks_controller.rb
  app/javascript/stylesheets/basic.scss
  app/models/user.rb
  app/views/devise/registrations/edit.html.slim
  app/views/devise/registrations/new.html.slim
  app/views/devise/sessions/new.html.slim
  config/initializers/devise.rb
  config/routes.rb
  db/migrate/20201129150927_add_omniauth_to_users.rb
  db/schema.rb
  spec/factories/users.rb
  spec/features/facebook_login_spec.rb
  spec/models/user_spec.rb
  spec/rails_helper.rb
  spec/support/login_form.rb
Labels: need review
