Repository IF-115-Ruby/OSBB, pull requests merged in 2020-12, with the labels that each got.

#105 add account to osbb
  app/controllers/account/admin/osbbs_controller.rb
  app/controllers/api/api_controller.rb
  app/controllers/api/v1/admin/osbbs_controller.rb
  app/helpers/about_helper.rb
  app/javascript/components/osbb/ShowOsbb.jsx
  app/javascript/components/osbb/Tab.jsx
  app/javascript/components/osbb/Tabs.jsx
  app/javascript/packs/application.js
  app/javascript/stylesheets/about.scss
  app/javascript/stylesheets/admin_form.scss
  app/javascript/stylesheets/application.scss
  app/javascript/stylesheets/show_osbb.scss
  app/models/account.rb
  app/models/company.rb
  app/models/osbb.rb
  app/views/account/admin/companies/show.html.slim
  app/views/account/admin/osbbs/show.html.slim
  app/views/api/v1/admin/osbbs/show.json.jbuilder
  app/views/home/about.html.slim
  config/routes.rb
  db/migrate/20201127134657_add_accountable_to_account.rb
  db/migrate/20201127134831_remove_reference_company.rb
  db/schema.rb
  db/seeds.rb
  spec/controllers/account/admin/osbbs_controller_spec.rb
  spec/controllers/api/v1/news_controller_spec.rb
  spec/factories/accounts.rb
  spec/features/osbbs_crud_spec.rb
  spec/models/account_spec.rb
Labels: !ready for review!, need merge

#118 add omniauth-google-oauth2
  Gemfile
  Gemfile.lock
  app/controllers/user/omniauth_callbacks_controller.rb
  app/models/user.rb
  app/views/devise/sessions/new.html.slim
  config/initializers/devise.rb
  spec/features/facebook_login_spec.rb
  spec/features/omniauth_login_spec.rb
  spec/support/login_form.rb
Labels: !ready for review!

#117 Crud for news on react
  app/controllers/api/v1/news_controller.rb
  app/javascript/components/my_osbb/News/Create/Create_news.jsx
  app/javascript/components/my_osbb/News/Edit/Edit_news.jsx
  app/javascript/components/my_osbb/News/News.jsx
  app/javascript/components/my_osbb/News/NewsForm.jsx
  app/javascript/components/my_osbb/News/NewsItem/NewsItem.jsx
  app/javascript/stylesheets/styles.scss
  app/views/account/news/edit.html.slim
  app/views/account/news/new.html.slim
  app/views/api/v1/news/index.json.jbuilder
  config/routes.rb
  package.json
  spec/controllers/api/v1/news_controller_spec.rb
  yarn.lock
Labels: need merge, need review

#101 DEMO #3 Fix
  Gemfile
  app/controllers/account/admin/companies_controller.rb
  app/controllers/account/admin/osbbs_controller.rb
  app/controllers/account/news_controller.rb
  app/javascript/components/my_osbb/News/News.jsx
  app/javascript/components/users/show/ShowUser.jsx
  app/javascript/components/users/show/_InfoHelper.jsx
  app/javascript/stylesheets/users.scss
  app/models/news.rb
  app/policies/news_policy.rb
  app/views/account/admin/users/_user.html.slim
  app/views/shared/account/_user_cabinet.html.slim
  spec/controllers/account/admin/companies_controller_spec.rb
  spec/controllers/account/admin/osbbs_controller_spec.rb
  spec/controllers/account/news_controller_spec.rb
  spec/support/shared_examples/not_found_examples.rb
Labels: !ready for review!, need merge

#125 fix bugs and specs after third demo
  app/controllers/account/admin/osbbs_controller.rb
  app/controllers/account/osbbs_controller.rb
  app/controllers/account/users_controller.rb
  app/views/account/admin/osbbs/_form.html.slim
  app/views/account/osbbs/search.json.jbuilder
  app/views/search_osbbs/_form.html.slim
  app/views/search_osbbs/search.json.jbuilder
  config/routes.rb
  spec/controllers/account/osbbs_controller_spec.rb
  spec/controllers/search_osbbs_controller_spec.rb
  spec/features/omniauth_login_spec.rb
  spec/features/osbbs_crud_spec.rb
  spec/features/user_assign_osbb_spec.rb
  spec/features/user_impersonate_spec.rb
Labels: need review

#127 add show osbb page for myosbb
  app/javascript/components/my_osbb/Menu/Menu.jsx
  app/javascript/components/my_osbb/MyOsbb.jsx
  app/javascript/components/osbb/ShowOsbb.jsx
  app/views/account/admin/osbbs/show.html.slim
  app/views/account/users/myosbb.html.slim
  config/routes.rb
Labels: need review

#129 Fix demo comments
  app/javascript/components/my_osbb/News/ShowNews.jsx
  db/schema.rb
  yarn.lock
Labels: !ready for review!, need merge

#131 fix seeds
  db/seeds.rb
Labels: need review

#111 OSBB posts crud on react for member
  app/controllers/account/users_controller.rb
  app/controllers/api/v1/posts_controller.rb
  app/javascript/components/my_osbb/Menu/Menu.jsx
  app/javascript/components/my_osbb/MyOsbb.jsx
  app/javascript/components/posts/CreatePost/CreatePost.jsx
  app/javascript/components/posts/CreatePost/CreatePost.module.scss
  app/javascript/components/posts/EditPost/EditPost.jsx
  app/javascript/components/posts/Posts.jsx
  app/javascript/components/posts/PostsForm.jsx
  app/javascript/components/posts/PostsIndex/Post.jsx
  app/javascript/components/posts/PostsIndex/Post.module.scss
  app/javascript/components/posts/PostsIndex/PostsIndex.jsx
  app/javascript/components/posts/PostsIndex/PostsIndex.module.scss
  app/javascript/components/posts/ShowPost/ShowItem.jsx
  app/javascript/components/posts/ShowPost/ShowItem.module.scss
  app/javascript/components/posts/ShowPost/ShowPost.jsx
  app/javascript/components/posts/ShowPost/ShowPost.module.scss
  app/javascript/components/posts/shared/Loading.jsx
  app/javascript/stylesheets/application.scss
  app/javascript/stylesheets/paginationBox.scss
  app/models/osbb.rb
  app/models/post.rb
  app/models/user.rb
  app/policies/post_policy.rb
  app/policies/user_policy.rb
  app/views/account/users/posts.html.slim
  app/views/api/v1/posts/_post.json.jbuilder
  app/views/api/v1/posts/index.json.jbuilder
  app/views/api/v1/posts/show.json.jbuilder
  app/views/shared/_footer.html.slim
  config/initializers/elasticsearch.rb
  config/routes.rb
  db/migrate/20201124205435_create_posts.rb
  db/migrate/20201223155544_add_index_to_posts.rb
  db/schema.rb
  db/seeds.rb
  package.json
  spec/controllers/api/v1/posts_controller_spec.rb
  spec/factories/posts.rb
  spec/models/post_spec.rb
  spec/policies/post_policy_spec.rb
  yarn.lock
Labels: need review

#110 Comments entity for news
  app/controllers/api/v1/comments_controller.rb
  app/javascript/components/my_osbb/MyUtilityProviders/MyUtilityProviders.jsx
  app/javascript/components/my_osbb/News/Comments/Comments.module.scss
  app/javascript/components/my_osbb/News/Comments/CommentsContainer.jsx
  app/javascript/components/my_osbb/News/Comments/EachComment.jsx
  app/javascript/components/my_osbb/News/Comments/Pagination.jsx
  app/javascript/components/my_osbb/News/Comments/_commentsHelper.js
  app/javascript/components/my_osbb/News/Comments/forms/CommentForm.jsx
  app/javascript/components/my_osbb/News/Comments/forms/Editor.jsx
  app/javascript/components/my_osbb/News/Comments/forms/ReplyForm.jsx
  app/javascript/components/my_osbb/News/Comments/requests.js
  app/javascript/components/my_osbb/News/NewsForm.jsx
  app/javascript/components/my_osbb/News/ShowNews.jsx
  app/javascript/components/my_osbb/News/ShowNews.module.scss
  app/javascript/services/http-service.js
  app/models/comment.rb
  app/models/news.rb
  app/models/user.rb
  app/views/account/news/show.html.slim
  app/views/account/payments/_payments.html.slim
  app/views/account/payments/receipt_pdf.html.slim
  app/views/api/v1/news/comments/_comment.json.jbuilder
  app/views/api/v1/news/comments/index.json.jbuilder
  app/views/api/v1/news/comments/update.json.jbuilder
  config/routes.rb
  db/migrate/20201115164451_create_comments.rb
  db/schema.rb
  db/seeds.rb
  package.json
  spec/controllers/api/v1/comments_controller_spec.rb
  spec/factories/comments.rb
  spec/models/comment_spec.rb
  spec/models/news_spec.rb
  spec/models/user_spec.rb
  yarn.lock
Labels: !ready for review!, need merge, need review
