Repository IF-115-Ruby/OSBB, pull requests merged in 2020-10, with the labels that each got.

#10 Add readme
  README.md
Labels: need review

#17 Fix user limits
  app/models/user.rb
  db/migrate/20201001185021_add_limit_user.rb
  db/schema.rb
  spec/factories/users.rb
  spec/models/user_spec.rb
Labels: !ready for review!

#18 crud_osbb
  .rspec
  .rubocop.yml
  Gemfile
  Gemfile.lock
  app/controllers/application_controller.rb
  app/controllers/osbbs_controller.rb
  app/javascript/stylesheets/application.scss
  app/javascript/stylesheets/osbbs.scss
  app/models/osbb.rb
  app/views/layouts/application.html.slim
  app/views/osbbs/_form.html.slim
  app/views/osbbs/_osbbs.html.slim
  app/views/osbbs/edit.html.slim
  app/views/osbbs/index.html.slim
  app/views/osbbs/new.html.slim
  app/views/osbbs/show.html.slim
  app/views/shared/_flash_msg.html.slim
  config/application.rb
  config/initializers/simple_form.rb
  config/locales/simple_form.en.yml
  config/routes.rb
  db/schema.rb
  lib/templates/slim/scaffold/_form.html.slim
  spec/controllers/osbbs_controller_spec.rb
  spec/features/osbbs_controller_crud_spec.rb
  spec/rails_helper.rb
  spec/spec_helper.rb
  test/application_system_test_case.rb
  test/channels/application_cable/connection_test.rb
  test/controllers/.keep
  test/fixtures/.keep
  test/fixtures/files/.keep
  test/helpers/.keep
  test/integration/.keep
  test/mailers/.keep
  test/models/.keep
  test/system/.keep
  test/test_helper.rb
Labels: !ready for review!

#19 Authentication User with Devise
  Gemfile
  Gemfile.lock
  app/controllers/application_controller.rb
  app/models/user.rb
  app/views/devise/registrations/edit.html.slim
  app/views/devise/registrations/new.html.slim
  app/views/devise/sessions/new.html.slim
  app/views/devise/shared/_error_messages.html.slim
  app/views/devise/shared/_links.html.slim
  app/views/shared/_header.html.slim
  config/initializers/devise.rb
  config/locales/devise.en.yml
  config/routes.rb
  db/migrate/20201001171736_add_devise_to_users.rb
  db/schema.rb
  spec/factories/users.rb
  spec/models/user_spec.rb
Labels: need merge

#22 Internationalization
  Gemfile
  Gemfile.lock
  app/controllers/application_controller.rb
  app/javascript/packs/application.js
  app/javascript/stylesheets/_colors.scss
  app/javascript/stylesheets/application.scss
  app/javascript/stylesheets/errors.scss
  app/javascript/stylesheets/osbbs.scss
  app/models/company.rb
  app/views/errors/not_found.html.slim
  app/views/errors/server_error.html.slim
  app/views/errors/unacceptable.html.slim
  app/views/home/index.html.slim
  app/views/layouts/application.html.slim
  app/views/shared/_footer.html.slim
  app/views/shared/_header.html.slim
  config/application.rb
  config/initializers/locale.rb
  config/locales/devise.ua.yml
  config/locales/en.yml
  config/locales/ua.yml
  config/routes.rb
  db/migrate/20201006171954_change_type_phone.rb
  db/schema.rb
  spec/factories/company.rb
  spec/models/company_spec.rb
Labels: need merge

#23 Update user model,combined with profile
  app/models/company.rb
  app/models/osbb.rb
  app/models/user.rb
  db/migrate/20201006074043_add_fields_to_users.rb
  db/migrate/20201006104325_add_group_to_users.rb
  db/schema.rb
  spec/factories/users.rb
  spec/models/user_spec.rb
Labels: need review

#21 BillingContracts
  app/controllers/billing_contracts_controller.rb
  app/helpers/billing_contracts_helper.rb
  app/javascript/stylesheets/application.scss
  app/javascript/stylesheets/billing_contracts.scss
  app/models/billing_contract.rb
  app/views/billing_contracts/_billing_contract.html.slim
  app/views/billing_contracts/_form.html.slim
  app/views/billing_contracts/edit.html.slim
  app/views/billing_contracts/index.html.slim
  app/views/billing_contracts/new.html.slim
  app/views/billing_contracts/show.html.slim
  app/views/layouts/application.html.slim
  app/views/osbbs/_form.html.slim
  app/views/osbbs/index.html.slim
  app/views/osbbs/show.html.slim
  config/locales/en.yml
  config/locales/ua.yml
  config/routes.rb
  db/migrate/20201005140257_create_billing_contracts.rb
  db/schema.rb
  db/seeds.rb
  spec/controllers/billing_contracts_controller_spec.rb
  spec/factories/billing_contracts.rb
  spec/helpers/billing_contracts_helper_spec.rb
  spec/models/billing_contract_spec.rb
Labels: need review

#27 [~]Hotfix for enums
  app/models/company.rb
  spec/factories/company.rb
  spec/factories/users.rb
Labels: need merge

#24 Add company associations
  app/models/account.rb
  app/models/address.rb
  app/models/company.rb
  app/models/osbb.rb
  app/models/user.rb
  app/views/layouts/application.html.slim
  db/migrate/20201007085314_create_accounts.rb
  db/migrate/20201007143134_create_addresses.rb
  db/migrate/20201009102408_add_account_association_to_company.rb
  db/schema.rb
  db/seeds.rb
  spec/factories/accounts.rb
  spec/factories/addresses.rb
  spec/factories/users.rb
  spec/models/account_spec.rb
  spec/models/address_spec.rb
  spec/models/company_spec.rb
  spec/models/osbb_spec.rb
  spec/models/user_spec.rb
Labels: need review

#25 User Index Show Update Destroy
  .gitignore
  Gemfile
  Gemfile.lock
  app/assets/images/User_Account.png
  app/assets/images/default_a.png
  app/controllers/billing_contracts_controller.rb
  app/controllers/users_controller.rb
  app/helpers/controller_helper.rb
  app/javascript/stylesheets/application.scss
  app/javascript/stylesheets/users.scss
  app/models/user.rb
  app/uploaders/avatar_uploader.rb
  app/views/users/_form.html.slim
  app/views/users/_user.html.slim
  app/views/users/edit.html.slim
  app/views/users/index.html.slim
  app/views/users/show.html.slim
  config/initializers/kaminari_config.rb
  config/routes.rb
  db/migrate/20201013163612_change_sex_to_users.rb
  db/schema.rb
  public/default_a.png
  spec/controllers/users_controller_spec.rb
  spec/factories/users.rb
  spec/helpers/controller_helper_spec.rb
  spec/models/user_spec.rb
Labels: need review

#29 Worked sign up and forgot password notifications
  .env.template
  Gemfile.lock
  app/controllers/application_controller.rb
  app/javascript/packs/application.js
  app/javascript/stylesheets/application.scss
  app/mailers/application_mailer.rb
  app/mailers/user_mailer.rb
  app/models/user.rb
  app/views/devise/mailer/reset_password_instructions.html.slim
  app/views/devise/passwords/edit.html.slim
  app/views/devise/passwords/new.html.slim
  app/views/devise/registrations/new.html.slim
  app/views/devise/sessions/new.html.slim
  app/views/devise/shared/_error_messages.html.slim
  app/views/devise/shared/_links.html.slim
  app/views/shared/_footer.html.slim
  app/views/shared/_header.html.slim
  app/views/user_mailer/send_welcome_email.html.slim
  config/environments/development.rb
  config/environments/production.rb
  config/environments/test.rb
  config/locales/en.yml
  config/locales/ua.yml
  config/routes.rb
  db/schema.rb
Labels: !ready for review!, need review

#35 added translation to users
  app/helpers/account/users_helper.rb
  app/javascript/stylesheets/users.scss
  app/views/account/admin/users/_user.html.slim
  app/views/account/admin/users/index.html.slim
  app/views/account/users/_form.html.slim
  app/views/account/users/edit.html.slim
  app/views/account/users/show.html.slim
  config/locales/en.yml
  config/locales/ua.yml
  spec/helpers/account/users_helper_spec.rb
Labels: !ready for review!, need merge, need review

#34 Sentry setup
  .env.template
  Gemfile
  Gemfile.lock
  app/controllers/application_controller.rb
  config/initializers/sentry.rb
Labels: need review

#31 CRUD companies and add ransack search
  Gemfile
  Gemfile.lock
  app/controllers/account/admin/companies_controller.rb
  app/javascript/stylesheets/application.scss
  app/javascript/stylesheets/companies.scss
  app/models/company.rb
  app/views/account/admin/companies/_company.html.slim
  app/views/account/admin/companies/_form.html.slim
  app/views/account/admin/companies/_search_form.html.slim
  app/views/account/admin/companies/edit.html.slim
  app/views/account/admin/companies/index.html.slim
  app/views/account/admin/companies/new.html.slim
  app/views/account/admin/companies/show.html.slim
  config/locales/en.yml
  config/locales/ua.yml
  config/routes.rb
  db/migrate/20201015161629_change_type_company_type.rb
  db/schema.rb
  spec/controllers/account/admin/companies_controller_spec.rb
Labels: !ready for review!, need review

#37 View log in, sign up, forgot password and change password with i18n
  Gemfile
  Gemfile.lock
  app/javascript/stylesheets/basic.scss
  app/views/devise/passwords/edit.html.slim
  app/views/devise/passwords/new.html.slim
  app/views/devise/registrations/new.html.slim
  app/views/devise/sessions/new.html.slim
  config/locales/en.yml
  config/locales/ua.yml
  spec/helpers/account/users_helper_spec.rb
Labels: !ready for review!

#36 add utility_providers
  .rubocop.yml
  app/controllers/account/admin/billing_contracts_controller.rb
  app/controllers/account/utility_providers_controller.rb
  app/helpers/billing_contracts_helper.rb
  app/javascript/stylesheets/application.scss
  app/javascript/stylesheets/utility_providers.scss
  app/models/billing_contract.rb
  app/models/company.rb
  app/models/user.rb
  app/views/account/admin/billing_contracts/_billing_contract.html.slim
  app/views/account/admin/billing_contracts/_form.html.slim
  app/views/account/admin/billing_contracts/edit.html.slim
  app/views/account/admin/billing_contracts/index.html.slim
  app/views/account/admin/billing_contracts/new.html.slim
  app/views/account/admin/billing_contracts/show.html.slim
  app/views/account/admin/companies/show.html.slim
  app/views/account/utility_providers/_search_form.html.slim
  app/views/account/utility_providers/companies.html.slim
  app/views/account/utility_providers/index.html.slim
  app/views/account/utility_providers/new.html.slim
  app/views/shared/account/_header.html.slim
  config/locales/en.yml
  config/locales/ua.yml
  config/routes.rb
  db/migrate/20201013063445_add_billing_contracts_associations_to_company.rb
  db/migrate/20201013084855_add_billing_contracts_associations_to_user.rb
  db/migrate/20201016150422_add_index_to_billing_contracts.rb
  db/schema.rb
  spec/controllers/account/admin/billing_contracts_controller_spec.rb
  spec/controllers/account/utility_providers_controller_spec.rb
  spec/factories/billing_contracts.rb
  spec/factories/company.rb
  spec/helpers/billing_contracts_helper_spec.rb
  spec/models/billing_contract_spec.rb
  spec/models/company_spec.rb
  spec/models/user_spec.rb
Labels: need review

#38 heroku and AWS setup
  Gemfile
  Gemfile.lock
  app/javascript/stylesheets/companies.scss
  app/javascript/stylesheets/users.scss
  app/models/user.rb
  app/uploaders/avatar_uploader.rb
  app/views/account/users/_form.html.slim
  app/views/layouts/account.html.slim
  bin/bundle
  bin/rails
  bin/rake
  config/application.rb
  config/environments/production.rb
  config/initializers/carrierwave.rb
  spec/models/user_spec.rb
  spec/support/images/image-3mb.jpg
  spec/support/images/image-3mb.txt
Labels: !ready for review!, need review

#42 Admin notification about new users
  .travis.yml
  app/mailers/admin_mailer.rb
  app/models/user.rb
  app/views/admin_mailer/admin_notification.html.slim
  app/views/devise/mailer/reset_password_instructions.html.slim
  app/views/user_mailer/send_welcome_email.html.slim
  config/locales/en.yml
  config/locales/ua.yml
  db/seeds.rb
  spec/mailers/admin_mailer_spec.rb
  spec/mailers/previews/admin_mailer_preview.rb
Labels: !ready for review!, need review

#40 added any_login gem, and configured it
  Gemfile
  Gemfile.lock
  app/models/user.rb
  app/views/layouts/application.html.slim
  config/initializers/any_login.rb
  spec/models/user_spec.rb
Labels: In Progress

#55 edit view for change password page
  app/controllers/account/utility_providers_controller.rb
  app/views/account/admin/user_cabinets/index.html.slim
  app/views/devise/registrations/edit.html.slim
  config/routes.rb
Labels: need merge, need review

#50 changed osbb views and account layout view
  .env.template
  app/controllers/account/admin/companies_controller.rb
  app/controllers/account/admin/osbbs_controller.rb
  app/controllers/account/admin/users_controller.rb
  app/controllers/osbbs_controller.rb
  app/javascript/stylesheets/_colors.scss
  app/javascript/stylesheets/account/style.scss
  app/javascript/stylesheets/admin_all_component.scss
  app/javascript/stylesheets/basic.scss
  app/javascript/stylesheets/osbbs.scss
  app/javascript/stylesheets/users.scss
  app/views/account/admin/osbbs/_form.html.slim
  app/views/account/admin/osbbs/_osbb.html.slim
  app/views/account/admin/osbbs/edit.html.slim
  app/views/account/admin/osbbs/index.html.slim
  app/views/account/admin/osbbs/new.html.slim
  app/views/account/admin/osbbs/show.html.slim
  app/views/account/admin/user_cabinets/index.html.slim
  app/views/errors/not_found.html.slim
  app/views/layouts/account.html.slim
  app/views/osbbs/_osbbs.html.slim
  app/views/osbbs/index.html.slim
  app/views/osbbs/show.html.slim
  app/views/shared/account/_header.html.slim
  config/locales/en.yml
  config/locales/ua.yml
  config/routes.rb
  spec/controllers/account/admin/osbbs_controller_spec.rb
  spec/controllers/osbbs_controller_spec.rb
  spec/features/osbbs_crud_spec.rb
Labels: need merge, need review
